# Use version 3 of the Docker Compose file format
version: '3'

services:
  app:
    # Name of the container
    container_name: fast-api-app
    # File containing environment variables
    env_file: .env
    # Build the Docker image from the current directory
    build: .
    # Command to run the FastAPI application using Uvicorn
    command: uvicorn src.api_report_analysis:app --host 0.0.0.0 --port 8000 --reload
    # Always restart the container if it stops
    restart: always
    # Map port 8001 on the host to port 8000 in the container
    ports:
      - "8001:8000"

